# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCwGjosInUzKcOA3Xx1NpW9ZGdso1AUg
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("/content/API_SP.POP.TOTL_DS2_en_csv_v2_2590.csv", skiprows=4)

print("Dataset:")
print(df)

print("Columns Names:\n",df.columns)

#Filter data for India Only
df_i=df[df['Country Name']=='India']

print("Indian Data:\n")
print(df_i)

years = [str(year) for year in range(1960, 2024)]  # 1960 to 2023
india_population = df_i[years].values.flatten()
print(india_population)

plt.figure(figsize=(16,6))
plt.bar(years, india_population, color='skyblue')
plt.title("India's Population (1960–2023)", fontsize=16)
plt.xlabel("Year", fontsize=12)
plt.ylabel("Population", fontsize=12)
plt.xticks(rotation=90)
plt.tight_layout()
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()